# Generated by Django 6.0.2 on 2026-07-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accusereception',
            name='est_annule',
            field=models.BooleanField(default=False, verbose_name='Annulé'),
        ),
        migrations.AddField(
            model_name='bonmouvement',
            name='est_annule',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='livraisonpartielle',
            name='est_annule',
            field=models.BooleanField(default=False, verbose_name='Annulé'),
        ),
    ]
