# Generated by Django 6.0.8 on 2026-08-14 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanInventaireTournant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Supprimé logiquement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du plan')),
                ('type_rotation', models.CharField(choices=[('PAR_FAMILLE', "Par famille d'articles"), ('PAR_ZONE', "Par zone / emplacement (toutes familles d'une zone)")], default='PAR_FAMILLE', max_length=20, verbose_name='Type de rotation')),
                ('frequence_jours', models.PositiveIntegerField(default=90, help_text='Intervalle entre deux comptages de la même famille/zone.', verbose_name='Fréquence (jours)')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif / En pause')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('prochaine_echeance', models.DateField(blank=True, help_text='Date à laquelle le prochain inventaire tournant sera généré.', null=True, verbose_name='Prochaine échéance')),
                ('dernier_comptage', models.DateTimeField(blank=True, help_text='Date de la dernière génération automatique.', null=True, verbose_name='Dernier comptage généré')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cree', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_supprimes', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('familles_cibles', models.ManyToManyField(blank=True, related_name='plans_inventaire_tournant', to='stock.famillearticle', verbose_name='Familles ciblées (rotation par famille)')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_inventaire_tournant', to='stock.magasin')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifie', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Plan d'inventaire tournant",
                'verbose_name_plural': "Plans d'inventaires tournants",
            },
        ),
    ]
