# Generated by Django 6.0.2 on 2026-08-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_inventaire_tournant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonmouvement',
            name='magasin_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_transferts_recus', to='stock.magasin', verbose_name='Magasin de destination (Transfert)'),
        ),
        migrations.AddField(
            model_name='historicalbonmouvement',
            name='magasin_destination',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.magasin', verbose_name='Magasin de destination (Transfert)'),
        ),
        migrations.AlterField(
            model_name='bonmouvement',
            name='type_bon',
            field=models.CharField(choices=[('ENTREE', "Bon d'Entrée (Réception)"), ('SORTIE', 'Bon de Sortie (Distribution)'), ('SORTIE_HORS_STOCK', 'Bon de Sortie Hors Stock (ENR-BSHS/DAF-002)'), ('RETOUR_FOURNISSEUR', 'Retour Fournisseur (Litige)'), ('RETOUR_SERVICE', "Retour d'un Service"), ('AJUSTEMENT', "Ajustement d'Inventaire"), ('TRANSFERT', 'Transfert inter-magasins')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalbonmouvement',
            name='type_bon',
            field=models.CharField(choices=[('ENTREE', "Bon d'Entrée (Réception)"), ('SORTIE', 'Bon de Sortie (Distribution)'), ('SORTIE_HORS_STOCK', 'Bon de Sortie Hors Stock (ENR-BSHS/DAF-002)'), ('RETOUR_FOURNISSEUR', 'Retour Fournisseur (Litige)'), ('RETOUR_SERVICE', "Retour d'un Service"), ('AJUSTEMENT', "Ajustement d'Inventaire"), ('TRANSFERT', 'Transfert inter-magasins')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalmouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée en stock'), ('SORTIE', 'Sortie de stock'), ('SORTIE_HORS_STOCK', 'Sortie Hors Stock (livraison directe)'), ('RETOUR_FOURNISSEUR', 'Retour au Fournisseur'), ('RETOUR_SERVICE', 'Retour depuis un Service'), ('AJUSTEMENT_POS', 'Ajustement Positif'), ('AJUSTEMENT_NEG', 'Ajustement Négatif'), ('AJUSTEMENT_NEG_FORCE', 'Ajustement Négatif Forcé (annulation)'), ('INVENTAIRE_POS', 'Inventaire Positif (écart constaté)'), ('INVENTAIRE_NEG', 'Inventaire Négatif (écart constaté)'), ('TRANSFERT_SORTIE', 'Sortie Transfert inter-magasins'), ('TRANSFERT_ENTREE', 'Entrée Transfert inter-magasins')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée en stock'), ('SORTIE', 'Sortie de stock'), ('SORTIE_HORS_STOCK', 'Sortie Hors Stock (livraison directe)'), ('RETOUR_FOURNISSEUR', 'Retour au Fournisseur'), ('RETOUR_SERVICE', 'Retour depuis un Service'), ('AJUSTEMENT_POS', 'Ajustement Positif'), ('AJUSTEMENT_NEG', 'Ajustement Négatif'), ('AJUSTEMENT_NEG_FORCE', 'Ajustement Négatif Forcé (annulation)'), ('INVENTAIRE_POS', 'Inventaire Positif (écart constaté)'), ('INVENTAIRE_NEG', 'Inventaire Négatif (écart constaté)'), ('TRANSFERT_SORTIE', 'Sortie Transfert inter-magasins'), ('TRANSFERT_ENTREE', 'Entrée Transfert inter-magasins')], db_index=True, max_length=30),
        ),
    ]
