# Generated by Django 6.0.2 on 2026-07-27 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_create_historical_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustement',
            name='numero_ajustement',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, verbose_name="Numéro d'ajustement"),
        ),
        migrations.AddField(
            model_name='historicalajustement',
            name='numero_ajustement',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, verbose_name="Numéro d'ajustement"),
        ),
        migrations.AlterField(
            model_name='compteurdocument',
            name='type_doc',
            field=models.CharField(choices=[('BON_SORTIE', 'Bon de Sortie'), ('BON_ENTREE', "Bon d'Entrée"), ('BON_RETOUR', 'Bon de Retour'), ('BON_HS', 'Bon Hors Stock'), ('COMMANDE', 'Commande'), ('DEMANDE', 'Demande'), ('AJUSTEMENT', 'Ajustement de Stock')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ajustement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('numero_ajustement__isnull', False)), fields=('numero_ajustement',), name='unique_ajustement_actif'),
        ),
    ]
