# Generated by Django 6.0.8 on 2026-08-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_transfert_inter_magasins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParametrePDF',
        ),
    ]
