# Generated by Django 6.0.8 on 2026-08-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_delete_parametrepdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonmouvement',
            options={'ordering': ['-date_bon'], 'permissions': [('can_add_bon_entree', "Peut créer des bons d'entrée"), ('can_add_bon_sortie', 'Peut créer des bons de sortie'), ('can_add_bon_retour', 'Peut créer des bons de retour'), ('can_add_bon_hors_stock', 'Peut créer des bons hors stock'), ('can_change_bon_entree', "Peut modifier des bons d'entrée"), ('can_change_bon_sortie', 'Peut modifier des bons de sortie'), ('can_change_bon_retour', 'Peut modifier des bons de retour'), ('can_change_bon_hors_stock', 'Peut modifier des bons hors stock'), ('can_cancel_bon_entree', "Peut annuler des bons d'entrée"), ('can_cancel_bon_sortie', 'Peut annuler des bons de sortie'), ('can_cancel_bon_retour', 'Peut annuler des bons de retour'), ('can_cancel_bon_hors_stock', 'Peut annuler des bons hors stock'), ('can_delete_bon_entree', "Peut supprimer des bons d'entrée"), ('can_delete_bon_sortie', 'Peut supprimer des bons de sortie'), ('can_delete_bon_retour', 'Peut supprimer des bons de retour'), ('can_delete_bon_hors_stock', 'Peut supprimer des bons hors stock')], 'verbose_name': 'Bon de mouvement', 'verbose_name_plural': 'Bons de mouvement'},
        ),
    ]
