# Generated by Django 6.1 on 2026-08-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmouvement',
            name='numero_lot',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstockitem',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='numero_lot',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
