# Generated by Django 6.1 on 2026-09-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_alter_historicalmouvement_numero_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famillearticle',
            name='methode_valorisation',
            field=models.CharField(blank=True, default='CMUP', help_text='Méthode de valorisation (ex: CMUP, FIFO, LIFO ou valeurs personnalisées)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='famillearticle',
            name='type_famille',
            field=models.CharField(blank=True, default='MED', help_text='Type de famille (ex: MED, MAT, BUR, TEC ou valeurs personnalisées)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfamillearticle',
            name='methode_valorisation',
            field=models.CharField(blank=True, default='CMUP', help_text='Méthode de valorisation (ex: CMUP, FIFO, LIFO ou valeurs personnalisées)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfamillearticle',
            name='type_famille',
            field=models.CharField(blank=True, default='MED', help_text='Type de famille (ex: MED, MAT, BUR, TEC ou valeurs personnalisées)', max_length=50, null=True),
        ),
    ]
