# Generated by Django 6.1 on 2026-09-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
        ('stock', '0034_clean_stale_pdf_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonmouvement',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_mouvement', to='projets.projet'),
        ),
        migrations.AddField(
            model_name='historicalbonmouvement',
            name='projet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projets.projet'),
        ),
        migrations.AlterField(
            model_name='bonmouvement',
            name='type_bon',
            field=models.CharField(choices=[('ENTREE', "Bon d'Entrée (Réception)"), ('SORTIE', 'Bon de Sortie (Distribution)'), ('SORTIE_PROJET', 'Sortie pour Projet'), ('SORTIE_HORS_STOCK', 'Bon de Sortie Hors Stock (ENR-BSHS/DAF-002)'), ('RETOUR_FOURNISSEUR', 'Retour Fournisseur (Litige)'), ('RETOUR_SERVICE', "Retour d'un Service"), ('RETOUR_PROJET', 'Retour de Projet (Reliquat)'), ('AJUSTEMENT', "Ajustement d'Inventaire"), ('TRANSFERT', 'Transfert inter-magasins')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalbonmouvement',
            name='type_bon',
            field=models.CharField(choices=[('ENTREE', "Bon d'Entrée (Réception)"), ('SORTIE', 'Bon de Sortie (Distribution)'), ('SORTIE_PROJET', 'Sortie pour Projet'), ('SORTIE_HORS_STOCK', 'Bon de Sortie Hors Stock (ENR-BSHS/DAF-002)'), ('RETOUR_FOURNISSEUR', 'Retour Fournisseur (Litige)'), ('RETOUR_SERVICE', "Retour d'un Service"), ('RETOUR_PROJET', 'Retour de Projet (Reliquat)'), ('AJUSTEMENT', "Ajustement d'Inventaire"), ('TRANSFERT', 'Transfert inter-magasins')], db_index=True, max_length=30),
        ),
    ]
