# Generated by Django 6.1 on 2026-09-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_bonmouvement_projet_historicalbonmouvement_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée en stock'), ('SORTIE', 'Sortie de stock'), ('SORTIE_PROJET', 'Sortie pour Projet'), ('SORTIE_HORS_STOCK', 'Sortie Hors Stock (livraison directe)'), ('RETOUR_FOURNISSEUR', 'Retour au Fournisseur'), ('RETOUR_SERVICE', 'Retour depuis un Service'), ('RETOUR_PROJET', 'Retour depuis un Projet'), ('AJUSTEMENT_POS', 'Ajustement Positif'), ('AJUSTEMENT_NEG', 'Ajustement Négatif'), ('AJUSTEMENT_NEG_FORCE', 'Ajustement Négatif Forcé (annulation)'), ('INVENTAIRE_POS', 'Inventaire Positif (écart constaté)'), ('INVENTAIRE_NEG', 'Inventaire Négatif (écart constaté)'), ('TRANSFERT_SORTIE', 'Sortie Transfert inter-magasins'), ('TRANSFERT_ENTREE', 'Entrée Transfert inter-magasins')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée en stock'), ('SORTIE', 'Sortie de stock'), ('SORTIE_PROJET', 'Sortie pour Projet'), ('SORTIE_HORS_STOCK', 'Sortie Hors Stock (livraison directe)'), ('RETOUR_FOURNISSEUR', 'Retour au Fournisseur'), ('RETOUR_SERVICE', 'Retour depuis un Service'), ('RETOUR_PROJET', 'Retour depuis un Projet'), ('AJUSTEMENT_POS', 'Ajustement Positif'), ('AJUSTEMENT_NEG', 'Ajustement Négatif'), ('AJUSTEMENT_NEG_FORCE', 'Ajustement Négatif Forcé (annulation)'), ('INVENTAIRE_POS', 'Inventaire Positif (écart constaté)'), ('INVENTAIRE_NEG', 'Inventaire Négatif (écart constaté)'), ('TRANSFERT_SORTIE', 'Sortie Transfert inter-magasins'), ('TRANSFERT_ENTREE', 'Entrée Transfert inter-magasins')], db_index=True, max_length=30),
        ),
    ]
