# Generated by Django 6.1 on 2026-09-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_alter_historicalmouvement_type_mouvement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmagasin',
            name='gere_projets',
            field=models.BooleanField(default=False, help_text='Si coché, ce magasin peut affecter du stock aux projets (entrées, sorties et retours de projets).', verbose_name='Gère les projets'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='gere_projets',
            field=models.BooleanField(default=False, help_text='Si coché, ce magasin peut affecter du stock aux projets (entrées, sorties et retours de projets).', verbose_name='Gère les projets'),
        ),
    ]
