# Generated by Django 6.1 on 2026-09-11 14:49

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_historicalmagasin_gere_projets_magasin_gere_projets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArticleFournisseur',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Supprimé logiquement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Prix d'achat fournisseur (FCFA)")),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence chez le fournisseur')),
                ('delai_livraison_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai de livraison (jours)')),
                ('est_principal', models.BooleanField(default=False, verbose_name='Fournisseur principal')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('article', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.article')),
                ('cree_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('fournisseur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.fournisseur')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'historical Tarif Fournisseur par Article',
                'verbose_name_plural': 'historical Tarifs Fournisseurs par Article',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Supprimé logiquement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Prix d'achat fournisseur (FCFA)")),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence chez le fournisseur')),
                ('delai_livraison_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai de livraison (jours)')),
                ('est_principal', models.BooleanField(default=False, verbose_name='Fournisseur principal')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_fournisseurs', to='stock.article')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cree', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_supprimes', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_fournisseur', to='stock.fournisseur')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifie', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Tarif Fournisseur par Article',
                'verbose_name_plural': 'Tarifs Fournisseurs par Article',
                'ordering': ['-est_principal', 'prix_achat'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('article', 'fournisseur'), name='unique_article_fournisseur_actif')],
            },
        ),
    ]
