# Generated by Django 6.1 on 2026-09-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0038_historicalarticlefournisseur_articlefournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmagasin',
            name='filtrer_articles_par_projet',
            field=models.BooleanField(default=True, help_text="Si activé, lorsqu'un magasinier choisit un projet, seuls les articles entrés ou prévus pour ce projet apparaissent dans la recherche.", verbose_name='Restreindre les articles aux matériels du projet'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='filtrer_articles_par_projet',
            field=models.BooleanField(default=True, help_text="Si activé, lorsqu'un magasinier choisit un projet, seuls les articles entrés ou prévus pour ce projet apparaissent dans la recherche.", verbose_name='Restreindre les articles aux matériels du projet'),
        ),
    ]
