# Generated by Django 6.1 on 2026-09-16 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0040_historicalmotifajustement_historicalunitemesure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmagasin',
            name='code_bon_entree',
        ),
        migrations.RemoveField(
            model_name='historicalmagasin',
            name='code_bon_hors_stock',
        ),
        migrations.RemoveField(
            model_name='historicalmagasin',
            name='code_bon_retour',
        ),
        migrations.RemoveField(
            model_name='historicalmagasin',
            name='code_bon_sortie',
        ),
        migrations.RemoveField(
            model_name='historicalmagasin',
            name='pied_de_page',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='code_bon_entree',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='code_bon_hors_stock',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='code_bon_retour',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='code_bon_sortie',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='pied_de_page',
        ),
        migrations.AlterField(
            model_name='historicalmagasin',
            name='gere_projets',
            field=models.BooleanField(default=False, help_text='Si actif, ce magasin peut affecter des entrées, sorties et retours à des projets (financement, subvention, activité spécifique).', verbose_name='Gère les projets'),
        ),
        migrations.AlterField(
            model_name='historicalmagasin',
            name='responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="La signature numérisée de cet utilisateur sera apposée sur les PDF (ex: 'Vu pour exécution').", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable / Signataire par défaut'),
        ),
        migrations.AlterField(
            model_name='historicalmagasin',
            name='titre_responsable',
            field=models.CharField(blank=True, help_text='Ex: Pharmacien Chef, Magasinier Principal', max_length=150, null=True, verbose_name='Titre du Responsable (PDF)'),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='gere_projets',
            field=models.BooleanField(default=False, help_text='Si actif, ce magasin peut affecter des entrées, sorties et retours à des projets (financement, subvention, activité spécifique).', verbose_name='Gère les projets'),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text="La signature numérisée de cet utilisateur sera apposée sur les PDF (ex: 'Vu pour exécution').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasins_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Responsable / Signataire par défaut'),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='titre_responsable',
            field=models.CharField(blank=True, help_text='Ex: Pharmacien Chef, Magasinier Principal', max_length=150, null=True, verbose_name='Titre du Responsable (PDF)'),
        ),
    ]
