# Generated by Django 6.0.2 on 2026-07-06 20:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationHopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Date de création (legacy)')),
                ('date_modification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dernière modification (legacy)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(default='CHU - Centre Hospitalier', max_length=200)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('type_mot_de_passe', models.CharField(choices=[('ALEATOIRE', '🔀 Aléatoire (sécurisé) — Le système génère un mot de passe fort'), ('FIXE', "🔒 Mot de passe fixe — L'admin définit un mot de passe par défaut")], default='ALEATOIRE', help_text='Choisissez comment les mots de passe sont attribués lors de la création de comptes.', max_length=20, verbose_name='Politique de mot de passe pour les nouveaux utilisateurs')),
                ('mot_de_passe_defaut', models.CharField(blank=True, help_text='Ce mot de passe sera utilisé pour tous les nouveaux comptes créés par les admins.', max_length=50, null=True, verbose_name="Mot de passe par défaut (si mode 'Fixe' choisit)")),
                ('delai_remplacement_bon_jours', models.PositiveIntegerField(default=2, verbose_name='Delai remplacement bon livraison (jours)')),
                ('obliger_reception_precedente', models.BooleanField(default=False, help_text='Si active, un utilisateur ne peut pas faire une nouvelle demande tant qu il n a pas signe l accuse de reception de sa livraison precedente.', verbose_name='Obliger la reception de la livraison precedente')),
                ('confidentialite_demandes', models.CharField(choices=[('PERSONNELLE', '👤 Personnelle — Chaque agent ne voit que SES propres demandes'), ('SERVICE', '👥 Par Service — Tous les agents du même service voient les demandes de leurs collègues')], default='PERSONNELLE', help_text="Définit qui peut voir les demandes dans 'Mes Demandes' : seulement le demandeur, ou tous les agents du même service.", max_length=20, verbose_name='Confidentialité des demandes de matériel')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(blank=True, help_text='TODO: null=False après backfill de toutes les configs existantes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations_hopital', to='accounts.entreprise')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalConfigurationHopital',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_creation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Date de création (legacy)')),
                ('date_modification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dernière modification (legacy)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(default='CHU - Centre Hospitalier', max_length=200)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('type_mot_de_passe', models.CharField(choices=[('ALEATOIRE', '🔀 Aléatoire (sécurisé) — Le système génère un mot de passe fort'), ('FIXE', "🔒 Mot de passe fixe — L'admin définit un mot de passe par défaut")], default='ALEATOIRE', help_text='Choisissez comment les mots de passe sont attribués lors de la création de comptes.', max_length=20, verbose_name='Politique de mot de passe pour les nouveaux utilisateurs')),
                ('mot_de_passe_defaut', models.CharField(blank=True, help_text='Ce mot de passe sera utilisé pour tous les nouveaux comptes créés par les admins.', max_length=50, null=True, verbose_name="Mot de passe par défaut (si mode 'Fixe' choisit)")),
                ('delai_remplacement_bon_jours', models.PositiveIntegerField(default=2, verbose_name='Delai remplacement bon livraison (jours)')),
                ('obliger_reception_precedente', models.BooleanField(default=False, help_text='Si active, un utilisateur ne peut pas faire une nouvelle demande tant qu il n a pas signe l accuse de reception de sa livraison precedente.', verbose_name='Obliger la reception de la livraison precedente')),
                ('confidentialite_demandes', models.CharField(choices=[('PERSONNELLE', '👤 Personnelle — Chaque agent ne voit que SES propres demandes'), ('SERVICE', '👥 Par Service — Tous les agents du même service voient les demandes de leurs collègues')], default='PERSONNELLE', help_text="Définit qui peut voir les demandes dans 'Mes Demandes' : seulement le demandeur, ou tous les agents du même service.", max_length=20, verbose_name='Confidentialité des demandes de matériel')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cree_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(blank=True, db_constraint=False, help_text='TODO: null=False après backfill de toutes les configs existantes.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.entreprise')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'historical configuration hopital',
                'verbose_name_plural': 'historical configuration hopitals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalService',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_creation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Date de création (legacy)')),
                ('date_modification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dernière modification (legacy)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Dernière modification')),
                ('poste', models.CharField(blank=True, default='', help_text='Ex: 231, 200, etc.', max_length=20, verbose_name='Poste / Extension')),
                ('code', models.CharField(help_text='Ex: SA17', max_length=20)),
                ('nom', models.CharField(help_text='Ex: CARDIOLOGIE, URGENCES', max_length=200)),
                ('poste_telephone', models.CharField(blank=True, help_text='Ex: 200, 256', max_length=20, null=True, verbose_name='Poste téléphonique')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('telecopie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Télécopie / Fax')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cree_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.entreprise')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'historical Service Hospitalier',
                'verbose_name_plural': 'historical Services Hospitaliers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Date de création (legacy)')),
                ('date_modification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dernière modification (legacy)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière modification')),
                ('poste', models.CharField(blank=True, default='', help_text='Ex: 231, 200, etc.', max_length=20, verbose_name='Poste / Extension')),
                ('code', models.CharField(help_text='Ex: SA17', max_length=20)),
                ('nom', models.CharField(help_text='Ex: CARDIOLOGIE, URGENCES', max_length=200)),
                ('poste_telephone', models.CharField(blank=True, help_text='Ex: 200, 256', max_length=20, null=True, verbose_name='Poste téléphonique')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('telecopie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Télécopie / Fax')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_core', to='accounts.entreprise')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Service Hospitalier',
                'verbose_name_plural': 'Services Hospitaliers',
            },
        ),
    ]
