# Generated by Django 6.0.2 on 2026-08-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activer_email', models.BooleanField(default=False, verbose_name='Activer les notifications par email')),
                ('smtp_host', models.CharField(blank=True, default='', help_text='Ex: smtp.gmail.com', max_length=200, verbose_name='Serveur SMTP (hôte)')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='Port SMTP')),
                ('smtp_user', models.CharField(blank=True, default='', max_length=200, verbose_name='Utilisateur SMTP')),
                ('smtp_password', models.CharField(blank=True, default='', max_length=200, verbose_name='Mot de passe SMTP')),
                ('email_expediteur', models.EmailField(blank=True, default='', help_text='Adresse affichée comme expéditeur des notifications.', max_length=254, verbose_name='Email expéditeur')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS (STARTTLS)')),
                ('activer_sms', models.BooleanField(default=False, verbose_name='Activer les notifications par SMS')),
                ('sms_provider', models.CharField(choices=[('GENERIQUE', 'API HTTP générique (URL + clé)'), ('TWILIO', 'Twilio'), ('TEST', 'Mode test (journal uniquement)')], default='TEST', max_length=20, verbose_name='Fournisseur SMS')),
                ('sms_api_url', models.URLField(blank=True, default='', help_text='Endpoint HTTP appelé pour envoyer un SMS (méthode POST).', max_length=300, verbose_name="URL de l'API SMS")),
                ('sms_api_key', models.CharField(blank=True, default='', help_text="Envoyée dans l'en-tête 'Authorization: Bearer <clé>'.", max_length=200, verbose_name='Clé API / Token')),
                ('sms_expediteur', models.CharField(blank=True, default='', max_length=20, verbose_name='Expéditeur (sender ID)')),
                ('sms_param_numero', models.CharField(default='to', help_text="Nom du champ JSON contenant le numéro de téléphone (ex: 'to').", max_length=50, verbose_name='Paramètre du numéro')),
                ('sms_param_message', models.CharField(default='message', help_text="Nom du champ JSON contenant le texte du SMS (ex: 'message').", max_length=50, verbose_name='Paramètre du message')),
                ('sms_mode_test', models.BooleanField(default=True, help_text="Si actif, les SMS sont journalisés dans les logs au lieu d'être réellement envoyés.", verbose_name='Mode test')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration des notifications',
                'verbose_name_plural': 'Configuration des notifications',
            },
        ),
    ]
