# Generated by Django 6.0.2 on 2026-08-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configurationnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationnotification',
            name='sms_twilio_template',
            field=models.CharField(blank=True, default='', help_text="Nom d'un modèle prédéfini Twilio (ex: sms_appointment_reminders). Obligatoire en compte trial : le texte libre est refusé (erreur 572006). Laisser vide en compte payant pour envoyer le vrai texte de la notification.", max_length=100, verbose_name='Modèle Twilio (compte trial)'),
        ),
    ]
