# -*- coding: utf-8 -*-
# Generated by Django 6.0.8 on 2026-08-15

"""Data migration : seed du service système « REBUTS ».

Le service REBUTS (DESTRUCTION / PÉREMPTIONS) est une donnée de référence
utilisée par le flux de destruction des lots périmés (livraison_service,
peremptions, rapports, sorties). Il doit vivre en base (donnée de référence)
et non être créé à la volée par le code applicatif.

Cette migration est idempotente : si le service existe déjà (créé par
l'ancien get_or_create du code), elle ne le duplique pas.
"""

from django.db import migrations


def creer_service_rebuts(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    # get_or_create avec historique : respecte la traçabilité sans dupliquer
    service, created = Service.objects.get_or_create(
        code='REBUTS',
        defaults={
            'nom': 'DESTRUCTION / PÉREMPTIONS',
            'poste': '',
            'poste_telephone': '',
            'telephone': '',
            'telecopie': '',
        },
    )
    if created:
        # Traçabilité (colonnes TraceabiliteMixin) — aucune valeur à poser ici,
        # les nullables le permettent ; on s'assure juste que le nom est bon.
        Service.objects.filter(pk=service.pk).update(nom='DESTRUCTION / PÉREMPTIONS')


def supprimer_service_rebuts(apps, schema_editor):
    """Reverse : retire le service REBUTS UNIQUEMENT s'il est orphelin
    (aucun mouvement/bon lié) — on ne détruit jamais des données d'exploitation.

    Les FK vers Service sont en PROTECT (BonMouvement.service_demandeur…) :
    s'il existe des données liées, la suppression échoue → la reverse de la
    migration est alors un no-op sûr (le service reste en base).
    """
    Service = apps.get_model('core', 'Service')
    try:
        Service.objects.filter(code='REBUTS').delete()
    except Exception:
        # Données liées : on ne casse pas la migration, on garde le service.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configurationnotification_sms_twilio_template'),
    ]

    operations = [
        migrations.RunPython(creer_service_rebuts, supprimer_service_rebuts),
    ]
