# Generated by Django 6.0.8 on 2026-08-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_service_rebuts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(choices=[('BS', 'Bon de Sortie'), ('BE', "Bon d'Entrée"), ('BR', 'Bon de Retour'), ('BSHS', 'Bon Hors Stock'), ('BDM', 'Bon de Demande de Matériel'), ('BC', 'Bon de Commande')], max_length=10, unique=True)),
                ('code_document', models.CharField(blank=True, max_length=50, verbose_name='Code document')),
                ('date_creation_doc', models.CharField(blank=True, max_length=20, verbose_name='Date création')),
                ('date_revision_doc', models.CharField(blank=True, max_length=20, verbose_name='Date révision')),
                ('version_doc', models.CharField(blank=True, max_length=10, verbose_name='Version')),
                ('ps2_label', models.CharField(blank=True, max_length=100, verbose_name='Label PS2')),
                ('afficher_logo', models.BooleanField(default=True, verbose_name='Afficher le logo')),
                ('afficher_cachet', models.BooleanField(default=True, verbose_name='Afficher le cachet')),
                ('afficher_cc', models.BooleanField(default=True, verbose_name='Afficher le CC')),
                ('afficher_ifu', models.BooleanField(default=True, verbose_name="Afficher l'IFU")),
                ('afficher_rccm', models.BooleanField(default=True, verbose_name='Afficher le RCCM')),
                ('afficher_telephone', models.BooleanField(default=True, verbose_name='Afficher le téléphone')),
                ('afficher_signatures', models.BooleanField(default=True, verbose_name='Afficher les signatures')),
            ],
            options={
                'verbose_name': 'Configuration document',
                'verbose_name_plural': 'Configurations documents',
                'ordering': ['type_doc'],
            },
        ),
    ]
