# Generated by Django 6.0.8 on 2026-08-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configdocument',
            name='afficher_cachet',
        ),
        migrations.RemoveField(
            model_name='configdocument',
            name='afficher_cc',
        ),
        migrations.RemoveField(
            model_name='configdocument',
            name='afficher_ifu',
        ),
        migrations.RemoveField(
            model_name='configdocument',
            name='afficher_logo',
        ),
        migrations.RemoveField(
            model_name='configdocument',
            name='afficher_rccm',
        ),
        migrations.RemoveField(
            model_name='configdocument',
            name='afficher_telephone',
        ),
        migrations.AddField(
            model_name='configurationhopital',
            name='afficher_cachet',
            field=models.BooleanField(default=True, verbose_name='Afficher le cachet sur les PDF'),
        ),
        migrations.AddField(
            model_name='configurationhopital',
            name='afficher_cc',
            field=models.BooleanField(default=True, verbose_name='Afficher le CC sur les PDF'),
        ),
        migrations.AddField(
            model_name='configurationhopital',
            name='afficher_ifu',
            field=models.BooleanField(default=True, verbose_name="Afficher l'IFU sur les PDF"),
        ),
        migrations.AddField(
            model_name='configurationhopital',
            name='afficher_logo',
            field=models.BooleanField(default=True, verbose_name='Afficher le logo sur les PDF'),
        ),
        migrations.AddField(
            model_name='configurationhopital',
            name='afficher_rccm',
            field=models.BooleanField(default=True, verbose_name='Afficher le RCCM sur les PDF'),
        ),
        migrations.AddField(
            model_name='configurationhopital',
            name='afficher_telephone',
            field=models.BooleanField(default=True, verbose_name='Afficher le téléphone sur les PDF'),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='afficher_cachet',
            field=models.BooleanField(default=True, verbose_name='Afficher le cachet sur les PDF'),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='afficher_cc',
            field=models.BooleanField(default=True, verbose_name='Afficher le CC sur les PDF'),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='afficher_ifu',
            field=models.BooleanField(default=True, verbose_name="Afficher l'IFU sur les PDF"),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='afficher_logo',
            field=models.BooleanField(default=True, verbose_name='Afficher le logo sur les PDF'),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='afficher_rccm',
            field=models.BooleanField(default=True, verbose_name='Afficher le RCCM sur les PDF'),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='afficher_telephone',
            field=models.BooleanField(default=True, verbose_name='Afficher le téléphone sur les PDF'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='pied_page_pdf',
            field=models.TextField(default='Document gǸnǸrǸ par NexusERP — Tous droits rǸservǸs.', verbose_name='Pied de page PDF'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='pied_page_pdf',
            field=models.TextField(default='Document gǸnǸrǸ par NexusERP — Tous droits rǸservǸs.', verbose_name='Pied de page PDF'),
        ),
    ]
