# Generated by Django 6.0.8 on 2026-08-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_configdocument_afficher_cachet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationhopital',
            name='afficher_devise',
            field=models.BooleanField(default=True, verbose_name='Afficher la Devise'),
        ),
        migrations.AddField(
            model_name='configurationhopital',
            name='afficher_direction',
            field=models.BooleanField(default=True, verbose_name='Afficher la Direction'),
        ),
        migrations.AddField(
            model_name='configurationhopital',
            name='afficher_republique',
            field=models.BooleanField(default=True, verbose_name='Afficher la République'),
        ),
        migrations.AddField(
            model_name='configurationhopital',
            name='afficher_service',
            field=models.BooleanField(default=True, verbose_name='Afficher le Service'),
        ),
        migrations.AddField(
            model_name='configurationhopital',
            name='afficher_sous_direction',
            field=models.BooleanField(default=True, verbose_name='Afficher la Sous-Direction'),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='afficher_devise',
            field=models.BooleanField(default=True, verbose_name='Afficher la Devise'),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='afficher_direction',
            field=models.BooleanField(default=True, verbose_name='Afficher la Direction'),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='afficher_republique',
            field=models.BooleanField(default=True, verbose_name='Afficher la République'),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='afficher_service',
            field=models.BooleanField(default=True, verbose_name='Afficher le Service'),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='afficher_sous_direction',
            field=models.BooleanField(default=True, verbose_name='Afficher la Sous-Direction'),
        ),
    ]
