# Generated by Django 6.0.8 on 2026-08-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configurationhopital_afficher_devise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationhopital',
            name='direction_label',
            field=models.CharField(blank=True, default='DIRECTION DES AFFAIRES FINANCIÈRES', max_length=200, verbose_name='Label Direction'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='label_signataire_1',
            field=models.CharField(blank=True, default='Le Demandeur', max_length=100, verbose_name='Signataire 1'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='label_signataire_2',
            field=models.CharField(blank=True, default='Le Magasinier', max_length=100, verbose_name='Signataire 2'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='label_signataire_3',
            field=models.CharField(blank=True, default='Le Responsable Service', max_length=100, verbose_name='Signataire 3'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='label_signataire_4',
            field=models.CharField(blank=True, default='Le Directeur', max_length=100, verbose_name='Signataire 4'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='label_signataire_5',
            field=models.CharField(blank=True, default='Le Contrôleur', max_length=100, verbose_name='Signataire 5'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='label_signataire_6',
            field=models.CharField(blank=True, default='Le Réceptionnaire', max_length=100, verbose_name='Signataire 6'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='pied_page_pdf',
            field=models.TextField(blank=True, default='Document gǸnǸrǸ par NexusERP — Tous droits rǸservǸs.', verbose_name='Pied de page PDF'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='prefixe_bon_entree',
            field=models.CharField(blank=True, default='BE', max_length=10, verbose_name="Préfixe Bon d'Entrée"),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='prefixe_bon_hors_stock',
            field=models.CharField(blank=True, default='BSHS', max_length=10, verbose_name='Préfixe Bon Hors Stock'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='prefixe_bon_retour',
            field=models.CharField(blank=True, default='BR', max_length=10, verbose_name='Préfixe Bon de Retour'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='prefixe_bon_sortie',
            field=models.CharField(blank=True, default='BS', max_length=10, verbose_name='Préfixe Bon de Sortie'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='prefixe_commande',
            field=models.CharField(blank=True, default='BC', max_length=10, verbose_name='Préfixe Commande'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='service_label',
            field=models.CharField(blank=True, default='SERVICE APPROVISIONNEMENT ET GESTION DES STOCKS', max_length=200, verbose_name='Label Service'),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='sous_direction_label',
            field=models.CharField(blank=True, default='SOUS-DIRECTION DE LA LOGISTIQUE', max_length=200, verbose_name='Label Sous-Direction'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='direction_label',
            field=models.CharField(blank=True, default='DIRECTION DES AFFAIRES FINANCIÈRES', max_length=200, verbose_name='Label Direction'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_1',
            field=models.CharField(blank=True, default='Le Demandeur', max_length=100, verbose_name='Signataire 1'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_2',
            field=models.CharField(blank=True, default='Le Magasinier', max_length=100, verbose_name='Signataire 2'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_3',
            field=models.CharField(blank=True, default='Le Responsable Service', max_length=100, verbose_name='Signataire 3'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_4',
            field=models.CharField(blank=True, default='Le Directeur', max_length=100, verbose_name='Signataire 4'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_5',
            field=models.CharField(blank=True, default='Le Contrôleur', max_length=100, verbose_name='Signataire 5'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_6',
            field=models.CharField(blank=True, default='Le Réceptionnaire', max_length=100, verbose_name='Signataire 6'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='pied_page_pdf',
            field=models.TextField(blank=True, default='Document gǸnǸrǸ par NexusERP — Tous droits rǸservǸs.', verbose_name='Pied de page PDF'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='prefixe_bon_entree',
            field=models.CharField(blank=True, default='BE', max_length=10, verbose_name="Préfixe Bon d'Entrée"),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='prefixe_bon_hors_stock',
            field=models.CharField(blank=True, default='BSHS', max_length=10, verbose_name='Préfixe Bon Hors Stock'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='prefixe_bon_retour',
            field=models.CharField(blank=True, default='BR', max_length=10, verbose_name='Préfixe Bon de Retour'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='prefixe_bon_sortie',
            field=models.CharField(blank=True, default='BS', max_length=10, verbose_name='Préfixe Bon de Sortie'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='prefixe_commande',
            field=models.CharField(blank=True, default='BC', max_length=10, verbose_name='Préfixe Commande'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='service_label',
            field=models.CharField(blank=True, default='SERVICE APPROVISIONNEMENT ET GESTION DES STOCKS', max_length=200, verbose_name='Label Service'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='sous_direction_label',
            field=models.CharField(blank=True, default='SOUS-DIRECTION DE LA LOGISTIQUE', max_length=200, verbose_name='Label Sous-Direction'),
        ),
    ]
