# Generated by Django 6.0.8 on 2026-08-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_configurationhopital_direction_label_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigDocument',
        ),
        migrations.RemoveField(
            model_name='configurationhopital',
            name='label_signataire_1',
        ),
        migrations.RemoveField(
            model_name='configurationhopital',
            name='label_signataire_2',
        ),
        migrations.RemoveField(
            model_name='configurationhopital',
            name='label_signataire_3',
        ),
        migrations.RemoveField(
            model_name='configurationhopital',
            name='label_signataire_4',
        ),
        migrations.RemoveField(
            model_name='configurationhopital',
            name='label_signataire_5',
        ),
        migrations.RemoveField(
            model_name='configurationhopital',
            name='label_signataire_6',
        ),
        migrations.RemoveField(
            model_name='configurationhopital',
            name='mot_de_passe_defaut',
        ),
        migrations.RemoveField(
            model_name='configurationhopital',
            name='type_mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_1',
        ),
        migrations.RemoveField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_2',
        ),
        migrations.RemoveField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_3',
        ),
        migrations.RemoveField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_4',
        ),
        migrations.RemoveField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_5',
        ),
        migrations.RemoveField(
            model_name='historicalconfigurationhopital',
            name='label_signataire_6',
        ),
        migrations.RemoveField(
            model_name='historicalconfigurationhopital',
            name='mot_de_passe_defaut',
        ),
        migrations.RemoveField(
            model_name='historicalconfigurationhopital',
            name='type_mot_de_passe',
        ),
    ]
