# Generated by Django 6.1 on 2026-08-24 21:54

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_configdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationnotification',
            name='sms_api_key',
            field=core.models.SecretCharField(blank=True, default='', help_text="Envoyée dans l'en-tête 'Authorization: Bearer <clé>'. Stockée chiffrée en base.", max_length=512, verbose_name='Clé API / Token'),
        ),
        migrations.AlterField(
            model_name='configurationnotification',
            name='smtp_password',
            field=core.models.SecretCharField(blank=True, default='', help_text='Stocké chiffré en base.', max_length=512, verbose_name='Mot de passe SMTP'),
        ),
    ]
