# Generated by Django 6.1 on 2026-09-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_configurationnotification_sms_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationhopital',
            name='pied_page_pdf',
            field=models.TextField(blank=True, default='Document généré par NexusERP — Tous droits réservés.', verbose_name='Pied de page PDF'),
        ),
        migrations.AlterField(
            model_name='historicalconfigurationhopital',
            name='pied_page_pdf',
            field=models.TextField(blank=True, default='Document généré par NexusERP — Tous droits réservés.', verbose_name='Pied de page PDF'),
        ),
    ]
