# Generated by Django 6.1 on 2026-09-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_configurationhopital_pied_page_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationhopital',
            name='devise_monetaire',
            field=models.CharField(default='FCFA', help_text="Symbole ou code de la devise monétaire affichée dans toute l'application.", max_length=15, verbose_name='Devise monétaire (ex: FCFA, EUR, $)'),
        ),
        migrations.AddField(
            model_name='configurationhopital',
            name='seuil_alerte_peremption_jours',
            field=models.PositiveIntegerField(default=30, help_text="Nombre de jours avant péremption pour déclencher l'alerte stock.", verbose_name="Délai d'alerte péremption (jours)"),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='devise_monetaire',
            field=models.CharField(default='FCFA', help_text="Symbole ou code de la devise monétaire affichée dans toute l'application.", max_length=15, verbose_name='Devise monétaire (ex: FCFA, EUR, $)'),
        ),
        migrations.AddField(
            model_name='historicalconfigurationhopital',
            name='seuil_alerte_peremption_jours',
            field=models.PositiveIntegerField(default=30, help_text="Nombre de jours avant péremption pour déclencher l'alerte stock.", verbose_name="Délai d'alerte péremption (jours)"),
        ),
    ]
