# Generated by Django 6.1 on 2026-09-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_configurationhopital_devise_monetaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservice',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='service',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='service',
            name='telephone',
        ),
    ]
