# Generated by Django 6.0.2 on 2026-08-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='devis_accepte',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Devis accept� ?'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='frais_hors_contrat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant devis hors contrat'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='motif_frais_hors_contrat',
            field=models.TextField(blank=True, default='', verbose_name='Motif des frais hors contrat'),
        ),
    ]
