# Generated by Django 6.0.2 on 2026-08-08 11:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0002_intervention_devis_accepte_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriepatrimoine',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Categorie patrimoine', 'verbose_name_plural': 'Categories patrimoine'},
        ),
        migrations.AlterModelOptions(
            name='parametrespatrimoine',
            options={'verbose_name': 'Parametres du Patrimoine', 'verbose_name_plural': 'Parametres du Patrimoine'},
        ),
        migrations.AlterModelOptions(
            name='typeequipement',
            options={'ordering': ['categorie', 'ordre', 'nom'], 'verbose_name': "Type d'equipement", 'verbose_name_plural': "Types d'equipements"},
        ),
        migrations.AlterField(
            model_name='batiment',
            name='code',
            field=models.CharField(blank=True, help_text='Genere automatiquement si vide (ex: BAT-001)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='campagneinventairepatrimoine',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ref. Inventaire'),
        ),
        migrations.AlterField(
            model_name='campagneinventairepatrimoine',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('TERMINEE', 'Terminee')], default='BROUILLON', max_length=50),
        ),
        migrations.AlterField(
            model_name='contratmaintenance',
            name='alerte_expiration_jours',
            field=models.PositiveSmallIntegerField(default=30, help_text='Nombre de jours avant expiration pour declencher une alerte'),
        ),
        migrations.AlterField(
            model_name='contratmaintenance',
            name='conditions_sla',
            field=models.TextField(blank=True, verbose_name="Conditions SLA / Delais d'intervention"),
        ),
        migrations.AlterField(
            model_name='contratmaintenance',
            name='reference',
            field=models.CharField(max_length=80, unique=True, verbose_name='Reference contrat'),
        ),
        migrations.AlterField(
            model_name='contratmaintenance',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expire'), ('SUSPENDU', 'Suspendu'), ('RESILIE', 'Resilie')], default='ACTIF', max_length=10),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='action_requise',
            field=models.CharField(choices=[('RAS', 'Aucune action requise'), ('MAINTENANCE', 'Maintenance preventive a planifier'), ('REPARATION', 'Reparation urgente'), ('REMPLACEMENT', 'Remplacement a prevoir'), ('REFORME', 'Mise au rebut a valider'), ('INVENTAIRE', "À verifier a l'inventaire")], default='RAS', max_length=20),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='date_mise_en_service',
            field=models.DateField(blank=True, help_text="Date reelle d'utilisation (= date_acquisition si non renseignee)", null=True),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='duree_amortissement_ans',
            field=models.PositiveSmallIntegerField(default=5, help_text='Heritee du TypeEquipement, modifiable par bien'),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='emplacement_exact',
            field=models.CharField(blank=True, help_text='Ex: Sur le bureau a gauche, Baie n°3 rack n°2', max_length=255),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='mode_amortissement',
            field=models.CharField(choices=[('LINEAIRE', 'Lineaire'), ('DEGRESSIF', 'Degressif')], default='LINEAIRE', max_length=10),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='nom_affichage',
            field=models.CharField(blank=True, help_text='Nom lisible, auto-genere si vide (ex: UC HP SDPCE)', max_length=200),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de serie'),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='reference_inventaire',
            field=models.CharField(blank=True, help_text="Reference du fichier d'inventaire source", max_length=50),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', "En attente d'immatriculation (Sas)"), ('ACTIF', 'En service / Actif'), ('EN_PANNE', 'En reparation / Panne'), ('REFORME', 'Reforme / Mis au rebut'), ('CEDE', 'Cede / Transfere'), ('DISPARU', 'Disparu / Perdu')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='valeur_residuelle',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valeur residuelle (FCFA)'),
        ),
        migrations.AlterField(
            model_name='importpatrimoine',
            name='statut',
            field=models.CharField(choices=[('OK', 'Succes'), ('PARTIEL', 'Partiel'), ('ECHEC', 'Échec')], default='OK', max_length=10),
        ),
        migrations.AlterField(
            model_name='importpatrimoine',
            name='type_equipement',
            field=models.ForeignKey(blank=True, help_text='Type cible par cet import (None = import generique)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimoine.typeequipement'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='actions_effectuees',
            field=models.TextField(blank=True, verbose_name='Actions effectuees'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='bon_sortie_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bons_sortie/generes/%Y/%m/', verbose_name='Bon de sortie genere (PDF)'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='bon_sortie_signe_scan',
            field=models.FileField(blank=True, null=True, upload_to='bons_sortie/signes/%Y/%m/', verbose_name='Bon de sortie signe par la securite/prestataire'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='demandes_pieces',
            field=models.ManyToManyField(blank=True, to='stock.demandemateriel', verbose_name='Demandes de pieces liees'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='description_probleme',
            field=models.TextField(verbose_name='Description du probleme'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='devis_accepte',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Devis accept ?'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='necessite_sortie_reparation',
            field=models.BooleanField(default=False, verbose_name='Le materiel doit sortir du CHU'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='interventions_photos/', verbose_name='Photo du probleme'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle demande'), ('PLANIFIEE', 'Planifiee'), ('EN_COURS', 'En cours'), ('EN_ATTENTE_PIECES', 'En attente de pieces'), ('EN_ATTENTE_VALIDATION', 'En attente de validation (Cloture)'), ('EN_ATTENTE_DEVIS', 'Attente validation Devis (Frais)'), ('RESOLUE', 'Resolue'), ('ESCALADEE', 'Escaladee / Non resolue'), ('ANNULEE', 'Annulee')], default='NOUVELLE', max_length=25),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technicien_appele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_recus', to='patrimoine.technicienprestataire', verbose_name='Contacte par telephone'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='type_intervention',
            field=models.CharField(choices=[('PREVENTIVE', 'Maintenance preventive'), ('CURATIVE', 'Maintenance curative (panne)'), ('URGENCE', 'Intervention urgente'), ('INVENTAIRE', 'Passage inventaire'), ('INSTALLATION', 'Installation / Mise en service')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ligneinventairepatrimoine',
            name='bureau_constate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimoine.bureau', verbose_name='Bureau ou la machine a ete vue'),
        ),
        migrations.AlterField(
            model_name='ligneinventairepatrimoine',
            name='etat_constate',
            field=models.CharField(blank=True, choices=[('PRESENT', 'Present et conforme'), ('DEPLACE', 'Present mais dans un autre bureau'), ('MANQUANT', 'Introuvable / Perdu'), ('A_REFORMER', "Present mais hors d'usage (À jeter)")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementpatrimoine',
            name='immobilisation_remplace',
            field=models.ForeignKey(blank=True, help_text='Bien remplace (si type = REMPLACEMENT)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacements', to='patrimoine.immobilisation'),
        ),
        migrations.AlterField(
            model_name='mouvementpatrimoine',
            name='type_mouvement',
            field=models.CharField(choices=[('AFFECTATION', 'Affectation initiale'), ('MUTATION', 'Mutation (changement de bureau)'), ('REPARATION', 'Sortie en reparation'), ('RETOUR_REPARATION', 'Retour apres reparation'), ('REFORME', 'Mise au rebut / Reforme'), ('REMPLACEMENT', 'Remplacement par un autre bien'), ('CESSION', 'Cession / Don'), ('PERTE', 'Perte / Vol constate')], max_length=25),
        ),
        migrations.AlterField(
            model_name='parametrespatrimoine',
            name='magasin_pieces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.magasin', verbose_name='Magasin par defaut pour les pieces detachees'),
        ),
        migrations.AlterField(
            model_name='parametrespatrimoine',
            name='mode_visibilite_interventions',
            field=models.CharField(choices=[('GLOBAL', "Mode Global : Tout le monde voit toutes les demandes d'intervention."), ('DIRECT', 'Mode Direct : Les demandes sont vues directement par le technicien concerne (selon sa specialite/domaine).'), ('DISPATCH', 'Mode Dispatch : Seul le chef voit les nouvelles demandes et les attribue aux techniciens.')], default='GLOBAL', max_length=20, verbose_name='Workflow de gestion des interventions'),
        ),
        migrations.AlterField(
            model_name='parametrespatrimoine',
            name='perimetre_declaration',
            field=models.CharField(choices=[('LIBRE', 'Libre (Tout le parc)'), ('SERVICE', 'Limite au Service'), ('BUREAU', 'Limite au Bureau')], default='LIBRE', max_length=20, verbose_name='Perimetre de declaration des pannes'),
        ),
        migrations.AlterField(
            model_name='typeequipement',
            name='duree_amortissement_defaut',
            field=models.PositiveSmallIntegerField(default=5, help_text="Duree d'amortissement par defaut en annees (modifiable par bien)"),
        ),
        migrations.AlterField(
            model_name='typeequipement',
            name='mode_amortissement',
            field=models.CharField(choices=[('LINEAIRE', 'Lineaire'), ('DEGRESSIF', 'Degressif')], default='LINEAIRE', max_length=10),
        ),
        migrations.AlterField(
            model_name='typeequipement',
            name='specs_schema',
            field=models.JSONField(blank=True, default=list, help_text='Definition des champs techniques propres a ce type'),
        ),
        migrations.AlterField(
            model_name='typeequipement',
            name='valeur_residuelle_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% de valeur residuelle a la fin (ex: 10 = 10% de la valeur initiale)', max_digits=5),
        ),
    ]
