# Generated by Django 6.0.2 on 2026-08-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0003_alter_categoriepatrimoine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratmaintenance',
            name='frequence_mois',
            field=models.PositiveSmallIntegerField(default=12, help_text='Fréquence des maintenances préventives (en mois, ex. 12 = annuelle, 6 = semestrielle)'),
        ),
    ]
