# Generated by Django 6.1 on 2026-08-27 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_configurationnotification_sms_api_key_and_more'),
        ('patrimoine', '0005_salleconference_reservationsalle_vehicule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('objet', models.CharField(max_length=255, verbose_name='Objet de la réunion')),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField(verbose_name='Date/heure début souhaitée')),
                ('date_fin', models.DateTimeField(verbose_name='Date/heure fin souhaitée')),
                ('nb_participants', models.PositiveSmallIntegerField(default=1)),
                ('besoin_videoconf', models.BooleanField(default=False)),
                ('besoin_video', models.BooleanField(default=False)),
                ('besoin_son', models.BooleanField(default=False)),
                ('notes_equipement', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=15)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cree', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_salle', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifie', to=settings.AUTH_USER_MODEL)),
                ('salle_attribuee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='patrimoine.salleconference')),
                ('salle_preferee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='patrimoine.salleconference')),
                ('service_demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_salle_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de salle',
                'verbose_name_plural': 'Demandes de salles',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='DemandeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('objet', models.CharField(max_length=255, verbose_name='Objet de la mission')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('date_depart', models.DateTimeField(verbose_name='Date/heure de départ souhaitée')),
                ('date_retour_prevue', models.DateTimeField(verbose_name='Date/heure de retour prévue')),
                ('nb_passagers', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de passagers')),
                ('urgency', models.CharField(choices=[('NORMALE', 'Normale'), ('URGENTE', 'Urgente'), ('CRITIQUE', 'Critique')], default='NORMALE', max_length=10)),
                ('motif', models.TextField(blank=True, verbose_name='Motif détaillé')),
                ('km_depart', models.PositiveIntegerField(blank=True, null=True)),
                ('km_retour', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée — véhicule affecté'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée par le demandeur'), ('TERMINEE', 'Terminée — véhicule rendu')], default='EN_ATTENTE', max_length=15)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('commentaire_valider', models.TextField(blank=True)),
                ('observation_retour', models.TextField(blank=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur_demandes', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cree', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_vehicule', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifie', to=settings.AUTH_USER_MODEL)),
                ('service_demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_vehicule_validees', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='patrimoine.vehicule')),
            ],
            options={
                'verbose_name': 'Demande de véhicule',
                'verbose_name_plural': 'Demandes de véhicules',
                'ordering': ['-date_demande'],
            },
        ),
    ]
