# Generated by Django 6.0.2 on 2026-07-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofil',
            name='doit_changer_mdp',
            field=models.BooleanField(default=True, verbose_name='Doit changer le mot de passe'),
        ),
        migrations.AddField(
            model_name='profil',
            name='doit_changer_mdp',
            field=models.BooleanField(default=True, verbose_name='Doit changer le mot de passe'),
        ),
    ]
