# Generated by Django 6.0.2 on 2026-07-06 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('patrimoine', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofil',
            name='bureau',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patrimoine.bureau', verbose_name='Bureau physique'),
        ),
        migrations.AddField(
            model_name='historicalprofil',
            name='cree_par',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprofil',
            name='entreprise',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.entreprise'),
        ),
        migrations.AddField(
            model_name='historicalprofil',
            name='fonction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.fonction', verbose_name='Fonction / Titre'),
        ),
        migrations.AddField(
            model_name='historicalprofil',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprofil',
            name='modifie_par',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprofil',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.service'),
        ),
        migrations.AddField(
            model_name='historicalprofil',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalspecialite',
            name='cree_par',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalspecialite',
            name='entreprise',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.entreprise'),
        ),
        migrations.AddField(
            model_name='historicalspecialite',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalspecialite',
            name='modifie_par',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='accounts.entreprise'),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profil',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='patrimoine.bureau', verbose_name='Bureau physique'),
        ),
        migrations.AddField(
            model_name='profil',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils_cree', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profil',
            name='domaines_intervention',
            field=models.ManyToManyField(blank=True, related_name='techniciens', to='patrimoine.categoriepatrimoine', verbose_name="Domaines d'intervention"),
        ),
        migrations.AddField(
            model_name='profil',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils', to='accounts.entreprise'),
        ),
        migrations.AddField(
            model_name='profil',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_fonction', to='accounts.fonction', verbose_name='Fonction / Titre'),
        ),
        migrations.AddField(
            model_name='profil',
            name='magasins_autorises',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs_autorises', to='stock.magasin'),
        ),
        migrations.AddField(
            model_name='profil',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils_modifie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profil',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='core.service'),
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleentreprise',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_entreprise', to='accounts.entreprise'),
        ),
        migrations.AddField(
            model_name='roleentreprise',
            name='groupe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roleentreprise', to='auth.group'),
        ),
        migrations.AddField(
            model_name='specialite',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialites_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialite',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='accounts.entreprise'),
        ),
        migrations.AddField(
            model_name='specialite',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialites_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profil',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='accounts.specialite'),
        ),
        migrations.AddField(
            model_name='historicalprofil',
            name='specialite',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.specialite'),
        ),
        migrations.AlterUniqueTogether(
            name='configdocument',
            unique_together={('entreprise', 'type_doc')},
        ),
        migrations.AlterUniqueTogether(
            name='fonction',
            unique_together={('entreprise', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='specialite',
            unique_together={('entreprise', 'nom')},
        ),
    ]
