# Generated by Django 6.0.2 on 2026-07-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_historicalprofil_doit_changer_mdp_and_more'),
    ]

    operations = [
    ]
