# Generated by Django 6.0.2 on 2026-07-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_entreprise_id_columns'),
    ]

    operations = [
    ]
