# Generated by Django 6.0.2 on 2026-07-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_entreprise_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mot_de_passe', models.CharField(choices=[('ALEATOIRE', 'Aléatoire (recommandé)'), ('FIXE', 'Mot de passe fixe')], default='ALEATOIRE', max_length=20, verbose_name="Mode d'attribution")),
                ('mot_de_passe_defaut', models.CharField(blank=True, default='', max_length=128, verbose_name='Mot de passe par défaut (mode fixe)')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration sécurité',
                'verbose_name_plural': 'Configuration sécurité',
            },
        ),
    ]
