# Generated by Django 6.0.2 on 2026-08-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profil_notif_email_notif_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofil',
            name='notif_email',
        ),
        migrations.RemoveField(
            model_name='historicalprofil',
            name='notif_sms',
        ),
    ]
