# Generated by Django 6.1 on 2026-08-07 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_menu_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuaccess',
            options={'permissions': [('menu_accueil', 'Accueil'), ('menu_dashboard', 'Tableau de bord'), ('menu_demandes', 'Demandes'), ('menu_valider_demandes', 'Valider Demandes'), ('menu_guichet', 'Guichet'), ('menu_livraisons', 'Livraisons'), ('menu_entrees', 'Entrées en Stock'), ('menu_reception_commande', 'Réceptions de commandes'), ('menu_sorties', 'Bons de Sortie'), ('menu_sorties_hors_stock', 'Sorties Hors Stock'), ('menu_retours_services', 'Retours Services'), ('menu_stock', 'État du Stock'), ('menu_peremptions', 'Péremptions'), ('menu_destructions', 'Destructions'), ('menu_ajustements', 'Ajustements'), ('menu_inventaires', 'Inventaires'), ('menu_historique', 'Historique'), ('menu_commandes', 'Commandes'), ('menu_articles', 'Articles'), ('menu_familles', 'Familles'), ('menu_fournisseurs', 'Fournisseurs'), ('menu_beneficiaires', 'Bénéficiaires'), ('menu_motifs_annulation', 'Motifs Annulation'), ('menu_magasins', 'Magasins'), ('menu_rapports', 'Rapports'), ('menu_stats_demandes', 'Stats Demandes'), ('menu_stats_sondages', 'Stats Sondages'), ('menu_pat_registre', 'Registre Patrimoine'), ('menu_pat_sas', "SAS (Zone d'attente)"), ('menu_pat_fiche_detail', 'Fiches Détaillées'), ('menu_pat_modifier_immo', 'Modifier Immobilisations'), ('menu_pat_mouvements', 'Mouvements Patrimoine'), ('menu_pat_eclatement', 'Éclatement Biens'), ('menu_pat_immatriculation', 'Immatriculation Directe'), ('menu_pat_qr_codes', 'Gestion QR Codes'), ('menu_pat_export_registre', 'Export Registre Excel'), ('menu_pat_import_excel', 'Import Excel Patrimoine'), ('menu_pat_contrats', 'Contrats'), ('menu_pat_contrat_detail', 'Détail Contrats'), ('menu_pat_assigner_equipements', 'Assigner Équipements aux Contrats'), ('menu_pat_interventions', 'Interventions'), ('menu_pat_intervention_detail', 'Détail Interventions'), ('menu_pat_signaler_panne', 'Signaler Panne'), ('menu_pat_creer_intervention', 'Créer Intervention'), ('menu_pat_valider_intervention', 'Valider Intervention'), ('menu_pat_portail_prestataire', 'Portail Prestataire'), ('menu_pat_schema_maintenance', 'Schémas Maintenance'), ('menu_pat_types_equipements', "Types d'Équipements"), ('menu_pat_tickets', 'Tickets SAV'), ('menu_pat_mes_tickets', 'Mes Tickets'), ('menu_pat_dispatch', 'Dispatch Interventions'), ('menu_pat_tech', 'Espace Technicien'), ('menu_pat_suivi_ticket', 'Suivi Ticket'), ('menu_pat_bon_sortie_reparation', 'Bon Sortie Réparation'), ('menu_pat_inventaire', 'Inventaire Parc'), ('menu_pat_campagnes_inventaire', 'Campagnes Inventaire'), ('menu_pat_detail_campagne', 'Détail Campagne'), ('menu_pat_reconciliation', 'Réconciliation Inventaire'), ('menu_pat_audit_scan', 'Audit Scan Inventaire'), ('menu_pat_fiche_comptage', 'Fiche Comptage'), ('menu_pat_rebuts', 'Rebuts'), ('menu_pat_pertes', 'Pertes'), ('menu_pat_parametres', 'Paramètres Patrimoine'), ('menu_pat_historique', 'Historique Patrimoine'), ('menu_utilisateurs', 'Utilisateurs'), ('menu_roles', 'Rôles'), ('menu_param_admin', 'Paramètres Admin'), ('menu_param_logistique', 'Paramètres Logistique'), ('menu_circuits_validation', 'Circuits Validation'), ('menu_securite_mdp', 'Sécurité MDP'), ('menu_journal_audit', 'Journal Audit'), ('menu_parametres', 'Paramètres Système'), ('menu_services', 'Services'), ('menu_specialites', 'Spécialités'), ('menu_fonctions', 'Fonctions & Titres'), ('menu_modeles_pdf', 'Modèles de documents PDF'), ('menu_parametres_doc', 'Configuration Documents PDF'), ('menu_lots', 'Gestion des Lots')], 'verbose_name': 'Accès Menu', 'verbose_name_plural': 'Accès Menus'},
        ),
        migrations.AlterField(
            model_name='auditconnexion',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_connexion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configdocument',
            name='type_doc',
            field=models.CharField(choices=[('BS', 'Bon de Sortie'), ('BE', "Bon d'Entrée"), ('BR', 'Bon de Retour'), ('BSHS', 'Bon Hors Stock'), ('BDM', 'Bon de Demande de Matériel'), ('BC', 'Bon de Commande')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='nom',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom de la fonction'),
        ),
        migrations.AlterField(
            model_name='historicalfonction',
            name='nom',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nom de la fonction'),
        ),
        migrations.AlterField(
            model_name='historicalspecialite',
            name='nom',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menuaccess',
            name='nom',
            field=models.CharField(choices=[('menu_accueil', 'Accueil'), ('menu_dashboard', 'Tableau de bord'), ('menu_demandes', 'Demandes'), ('menu_valider_demandes', 'Valider Demandes'), ('menu_guichet', 'Guichet'), ('menu_livraisons', 'Livraisons'), ('menu_entrees', 'Entrées en Stock'), ('menu_reception_commande', 'Réceptions de commandes'), ('menu_sorties', 'Bons de Sortie'), ('menu_sorties_hors_stock', 'Sorties Hors Stock'), ('menu_retours_services', 'Retours Services'), ('menu_stock', 'État du Stock'), ('menu_peremptions', 'Péremptions'), ('menu_destructions', 'Destructions'), ('menu_ajustements', 'Ajustements'), ('menu_inventaires', 'Inventaires'), ('menu_historique', 'Historique'), ('menu_commandes', 'Commandes'), ('menu_articles', 'Articles'), ('menu_familles', 'Familles'), ('menu_fournisseurs', 'Fournisseurs'), ('menu_beneficiaires', 'Bénéficiaires'), ('menu_motifs_annulation', 'Motifs Annulation'), ('menu_magasins', 'Magasins'), ('menu_rapports', 'Rapports'), ('menu_stats_demandes', 'Stats Demandes'), ('menu_stats_sondages', 'Stats Sondages'), ('menu_pat_registre', 'Registre Patrimoine'), ('menu_pat_sas', "SAS (Zone d'attente)"), ('menu_pat_fiche_detail', 'Fiches Détaillées'), ('menu_pat_modifier_immo', 'Modifier Immobilisations'), ('menu_pat_mouvements', 'Mouvements Patrimoine'), ('menu_pat_eclatement', 'Éclatement Biens'), ('menu_pat_immatriculation', 'Immatriculation Directe'), ('menu_pat_qr_codes', 'Gestion QR Codes'), ('menu_pat_export_registre', 'Export Registre Excel'), ('menu_pat_import_excel', 'Import Excel Patrimoine'), ('menu_pat_contrats', 'Contrats'), ('menu_pat_contrat_detail', 'Détail Contrats'), ('menu_pat_assigner_equipements', 'Assigner Équipements aux Contrats'), ('menu_pat_interventions', 'Interventions'), ('menu_pat_intervention_detail', 'Détail Interventions'), ('menu_pat_signaler_panne', 'Signaler Panne'), ('menu_pat_creer_intervention', 'Créer Intervention'), ('menu_pat_valider_intervention', 'Valider Intervention'), ('menu_pat_portail_prestataire', 'Portail Prestataire'), ('menu_pat_schema_maintenance', 'Schémas Maintenance'), ('menu_pat_types_equipements', "Types d'Équipements"), ('menu_pat_tickets', 'Tickets SAV'), ('menu_pat_mes_tickets', 'Mes Tickets'), ('menu_pat_dispatch', 'Dispatch Interventions'), ('menu_pat_tech', 'Espace Technicien'), ('menu_pat_suivi_ticket', 'Suivi Ticket'), ('menu_pat_bon_sortie_reparation', 'Bon Sortie Réparation'), ('menu_pat_inventaire', 'Inventaire Parc'), ('menu_pat_campagnes_inventaire', 'Campagnes Inventaire'), ('menu_pat_detail_campagne', 'Détail Campagne'), ('menu_pat_reconciliation', 'Réconciliation Inventaire'), ('menu_pat_audit_scan', 'Audit Scan Inventaire'), ('menu_pat_fiche_comptage', 'Fiche Comptage'), ('menu_pat_rebuts', 'Rebuts'), ('menu_pat_pertes', 'Pertes'), ('menu_pat_parametres', 'Paramètres Patrimoine'), ('menu_pat_historique', 'Historique Patrimoine'), ('menu_utilisateurs', 'Utilisateurs'), ('menu_roles', 'Rôles'), ('menu_param_admin', 'Paramètres Admin'), ('menu_param_logistique', 'Paramètres Logistique'), ('menu_circuits_validation', 'Circuits Validation'), ('menu_securite_mdp', 'Sécurité MDP'), ('menu_journal_audit', 'Journal Audit'), ('menu_parametres', 'Paramètres Système'), ('menu_services', 'Services'), ('menu_specialites', 'Spécialités'), ('menu_fonctions', 'Fonctions & Titres'), ('menu_modeles_pdf', 'Modèles de documents PDF'), ('menu_parametres_doc', 'Configuration Documents PDF'), ('menu_lots', 'Gestion des Lots')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
