# Generated by Django 6.0.8 on 2026-08-04 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_menu_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configdocument',
            name='afficher_cachet',
        ),
        migrations.AlterField(
            model_name='auditconnexion',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_connexion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configdocument',
            name='type_doc',
            field=models.CharField(choices=[('BS', 'Bon de Sortie'), ('BE', "Bon d'Entrée"), ('BR', 'Bon de Retour'), ('BSHS', 'Bon Hors Stock'), ('BDM', 'Bon de Demande de Matériel'), ('BC', 'Bon de Commande')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='nom',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom de la fonction'),
        ),
        migrations.AlterField(
            model_name='historicalfonction',
            name='nom',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nom de la fonction'),
        ),
        migrations.AlterField(
            model_name='historicalspecialite',
            name='nom',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
