# Generated by Django 6.1 on 2026-08-07 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_patrimoine_permissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuaccess',
            options={'ordering': ['ordre', 'nom'], 'permissions': [('menu_pat_registre', 'Registre Patrimoine'), ('menu_pat_sas', "SAS (Zone d'attente)"), ('menu_pat_fiche_detail', 'Fiches Détaillées'), ('menu_pat_modifier_immo', 'Modifier Immobilisations'), ('menu_pat_mouvements', 'Mouvements Patrimoine'), ('menu_pat_eclatement', 'Éclatement Biens'), ('menu_pat_immatriculation', 'Immatriculation Directe'), ('menu_pat_qr_codes', 'Gestion QR Codes'), ('menu_pat_export_registre', 'Export Registre Excel'), ('menu_pat_import_excel', 'Import Excel Patrimoine'), ('menu_pat_contrats', 'Contrats'), ('menu_pat_contrat_detail', 'Détail Contrats'), ('menu_pat_assigner_equipements', 'Assigner Équipements aux Contrats'), ('menu_pat_interventions', 'Interventions'), ('menu_pat_intervention_detail', 'Détail Interventions'), ('menu_pat_signaler_panne', 'Signaler Panne'), ('menu_pat_creer_intervention', 'Créer Intervention'), ('menu_pat_valider_intervention', 'Valider Intervention'), ('menu_pat_portail_prestataire', 'Portail Prestataire'), ('menu_pat_schema_maintenance', 'Schémas Maintenance'), ('menu_pat_types_equipements', "Types d'Équipements"), ('menu_pat_tickets', 'Tickets SAV'), ('menu_pat_mes_tickets', 'Mes Tickets'), ('menu_pat_dispatch', 'Dispatch Interventions'), ('menu_pat_tech', 'Espace Technicien'), ('menu_pat_suivi_ticket', 'Suivi Ticket'), ('menu_pat_bon_sortie_reparation', 'Bon Sortie Réparation'), ('menu_pat_inventaire', 'Inventaire Parc'), ('menu_pat_campagnes_inventaire', 'Campagnes Inventaire'), ('menu_pat_detail_campagne', 'Détail Campagne'), ('menu_pat_reconciliation', 'Réconciliation Inventaire'), ('menu_pat_audit_scan', 'Audit Scan Inventaire'), ('menu_pat_fiche_comptage', 'Fiche Comptage'), ('menu_pat_rebuts', 'Rebuts'), ('menu_pat_pertes', 'Pertes'), ('menu_pat_parametres', 'Paramètres Patrimoine'), ('menu_pat_historique', 'Historique Patrimoine')], 'verbose_name': 'Accès Menu', 'verbose_name_plural': 'Accès Menus'},
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='code',
            field=models.CharField(default='menu_inconnu', max_length=100, unique=True, verbose_name='Code permission'),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='menus_accessibles', to='auth.group', verbose_name='Groupes autorisés'),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='icone',
            field=models.CharField(blank=True, default='fa-circle', max_length=50, verbose_name='Icône FontAwesome'),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=100, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_menus', to='accounts.menuaccess', verbose_name='Menu parent'),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=255, verbose_name='URL cible'),
        ),
        migrations.AlterField(
            model_name='menuaccess',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='menuaccess',
            name='nom',
            field=models.CharField(default='Menu Inconnu', max_length=150, verbose_name='Nom affiché'),
        ),
    ]
