# Generated by Django 6.0.2 on 2026-08-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_patrimoine_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuaccess',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Accès Menu / Permission', 'verbose_name_plural': 'Accès Menus / Permissions'},
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='code',
            field=models.CharField(default=1, help_text='Code unique pour les permissions (ex: menu_pat_registre)', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='icone',
            field=models.CharField(default='fa-circle', help_text='Classe FontAwesome (ex: fa-box)', max_length=50),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='ordre',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Menu parent (laisser vide pour un menu racine)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_menus', to='accounts.menuaccess'),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='url',
            field=models.CharField(blank=True, help_text='URL de la page', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menuaccess',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
