# Generated by Django 6.0.2 on 2026-08-11 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_historicalprofil_notif_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='est_importante',
            field=models.BooleanField(default=False, help_text="Si activée, la notification est aussi envoyée par SMS. Les notifications ordinaires ne partent que par email et dans la cloche (les SMS coûtent de l'argent : réservés aux cas importants).", verbose_name='Notification importante'),
        ),
        migrations.CreateModel(
            name='MotDePasseResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(db_index=True, max_length=8, verbose_name='Code SMS')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField(verbose_name='Expiration')),
                ('utilise', models.BooleanField(default=False, verbose_name='Déjà utilisé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_reset_mdp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jeton de réinitialisation de mot de passe',
                'verbose_name_plural': 'Jetons de réinitialisation de mot de passe',
                'ordering': ['-cree_le'],
            },
        ),
    ]
