# Generated by Django 6.0.2 on 2026-08-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_menuaccess_options_menuaccess_actif_and_more'),
        ('accounts', '0008_update_menuaccess_structure'),
    ]

    operations = [
    ]
