# Generated by Django 6.0.8 on 2026-08-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_menu_retours_fournisseurs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigDocument',
        ),
    ]
