# Generated by Django 6.1 on 2026-09-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_menuaccess_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditconnexion',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Clé de session Django'),
        ),
    ]
