"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""
import os
import dj_database_url
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ✅ CORRECTION : DEBUG depuis variable d'environnement.
# Défaut FAIL-SAFE : sans DJANGO_DEBUG explicite, l'app démarre en mode
# production (DEBUG=False). En développement local, lancer avec
# DJANGO_DEBUG=True (voir .freebuff/run.md).
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

# ✅ CORRECTION : SECRET_KEY lu depuis l'environnement.
# Le fallback en dur n'est autorisé qu'en développement (DEBUG=True).
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = '8KWj8QB8VcDHFbWddy-6RrMemVPyGHthFZZtfJe1Ew0SQLC9KwnPndgfGlv5zYlwVY4'  # dev uniquement
    else:
        raise ImproperlyConfigured(
            "La variable d'environnement DJANGO_SECRET_KEY doit être définie en production."
        )

DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # mes modules :
    'core',
    'stock',
    'accounts',
    'simple_history',
    'patrimoine.apps.PatrimoineConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'accounts.middleware.AntiSpamMiddleware',
    'accounts.middleware.PasswordChangeMiddleware',
    'accounts.middleware.ThemeMiddleware',
    'accounts.middleware.MagasinAutoSelectMiddleware',  
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'stock.context_processors.contexte_magasin',
                'stock.context_processors.notifications_erp',
                'stock.context_processors.validation_menu_context',
                'stock.context_processors.validation_demandes_menu',
                'stock.context_processors.menu_validation_context',
                # ✅ CORRECTION : sélecteur d'établissement supprimé (mono-tenant)
                'accounts.context_processors.theme_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# PostgreSQL est la SEULE base de données supportée (production, staging,
# développement et tests). Aucun autre moteur (SQLite, MySQL...) n'est
# accepté : les migrations, le SQL et les tests sont écrits pour Postgres.
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
    }
else:
    if not os.environ.get('DB_PASSWORD') and not DEBUG:
        raise ImproperlyConfigured(
            "La variable d'environnement DB_PASSWORD doit être définie en production."
        )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'chu_angre_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'admin'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),  # pool connexions (10 min)
            'CONN_HEALTH_CHECKS': True,  # Django 5.1+ : vérifie la santé des connexions
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'fr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# ── Cache en mémoire (évite les requêtes répétées sur les mêmes données)
# En production, remplacer par Redis si dispo : CACHES = { 'default': { 'BACKEND': 'django.core.cache.backends.redis.RedisCache', ... } }
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'nexuserp-unique-snowflake',  # isole ce cache du cache global Django
        'TIMEOUT': 300,  # 5 minutes par défaut
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Clé primaire par défaut : BigInt (évite les overflow sur 2^31)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Securite renforcee (ERP sante)
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS : 'SAMEORIGIN' (défini plus bas) est volontaire :
# nécessaire pour les aperçus PDF affichés en iframe sur le même site.
# On silencie donc le warning security.W019 (DENY impossible ici).
SILENCED_SYSTEM_CHECKS = ['security.W019']
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

# ── Dual IP : mode TRUSTED� correspond à des serveurs internes sans SSL ──
# En mode interne (pas de proxy HTTPS), désactive la redirection SSL.
if not DEBUG and os.environ.get('TRUSTED_INTERNAL', '0') == '1':
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0

# --- CONFIGURATION DE LA CONNEXION (Module accounts) ---
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# --- SÉCURITÉ DES SESSIONS ---
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 1200               # 20 minutes = 1200 secondes
# ✅ False : ne sauvegarde PAS la session à chaque clic (réduit la charge DB).
# La session expire 20 min après le dernier rechargement de page
# (suffisant car la plupart des pages rechargent déjà).
SESSION_SAVE_EVERY_REQUEST = False


# Autoriser l'affichage des fenêtres pop-up (iframes) sur le même site
X_FRAME_OPTIONS = 'SAMEORIGIN'

# URL publique pour accéder aux fichiers
MEDIA_URL = '/media/'

# Dossier physique où les fichiers sont stockés
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# ✅ CORRECTION : Backend standard Django (plus de TenantAwareBackend)
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# ── Journalisation des requêtes lentes ────────────────────────────────
# Le logger django.db.backends reçoit chaque requête SQL avec son attribut
# `duration` (secondes) quand le curseur de debug est actif (DEBUG=True en
# dev, ou force_debug_cursor activé par le signal connection_created en prod).
# SlowQueryFilter ne garde que celles ≥ 200 ms, écrites dans
# logs/slow-queries.log (surveillées par le tableau de bord /supervision/).
# Désactivable avec SLOW_QUERY_LOG=0 ; inactif en TEST_MODE (pas d'écriture
# disque dans les tests).
if (os.environ.get('TEST_MODE', 'False').lower() not in ('true', '1', 'yes')
        and os.environ.get('SLOW_QUERY_LOG', '1') != '0'):
    _LOGS_DIR = BASE_DIR / 'logs'
    _LOGS_DIR.mkdir(parents=True, exist_ok=True)
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'filters': {
            'slow_queries': {
                '()': 'core.logging_filters.SlowQueryFilter',
                'threshold': 0.2,  # secondes
            },
        },
        'formatters': {
            'simple': {
                'format': '[{asctime}] {levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'slow_queries_file': {
                'level': 'DEBUG',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': str(_LOGS_DIR / 'slow-queries.log'),
                'maxBytes': 5 * 1024 * 1024,   # 5 Mo
                'backupCount': 3,
                'formatter': 'simple',
                'filters': ['slow_queries'],
            },
        },
        'loggers': {
            'django.db.backends': {
                'level': 'DEBUG',
                'handlers': ['slow_queries_file'],
                'propagate': False,
            },
        },
    }
    # En production (DEBUG=False), le curseur de debug n'est pas actif par
    # défaut — on l'active à la création de chaque connexion pour que les
    # durées soient mesurées (signal idiomatique Django).
    if not DEBUG:
        from django.db.backends.signals import connection_created

        def _activer_suivi_requetes(sender, connection, **kwargs):  # noqa: ARG001
            connection.force_debug_cursor = True

        connection_created.connect(
            _activer_suivi_requetes, dispatch_uid='nexuserp_slow_query_log'
        )


# ── Sécurité ─────────────────────────────────────────────────────────
# Activer UNIQUEMENT si l'application est derrière un reverse proxy qui
# écrase X-Forwarded-For (nginx, traefik…). Sinon, rester False : un
# client peut spoof cet en-tête pour contourner l'anti brute-force IP.
USE_X_FORWARDED_FOR = False


# ── Durcissement production (actif UNIQUEMENT hors DEBUG) ────────────
# SECURE_SSL_REDIRECT suppose un reverse proxy qui termine le HTTPS
# (nginx/traefik) et écrase X-Forwarded-Proto (cf. USE_X_FORWARDED_FOR).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
