"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""
import os
import dj_database_url
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ✅ CORRECTION : DEBUG depuis variable d'environnement
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

# ✅ CORRECTION : SECRET_KEY lu depuis l'environnement.
# Le fallback en dur n'est autorisé qu'en développement (DEBUG=True).
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = '8KWj8QB8VcDHFbWddy-6RrMemVPyGHthFZZtfJe1Ew0SQLC9KwnPndgfGlv5zYlwVY4'  # dev uniquement
    else:
        raise ImproperlyConfigured(
            "La variable d'environnement DJANGO_SECRET_KEY doit être définie en production."
        )

DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # mes modules :
    'core',
    'stock',
    'accounts',
    'simple_history',
    'patrimoine.apps.PatrimoineConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'accounts.middleware.AntiSpamMiddleware',
    'accounts.middleware.PasswordChangeMiddleware',
    'accounts.middleware.ThemeMiddleware',
    'accounts.middleware.MagasinAutoSelectMiddleware',  
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'stock.context_processors.contexte_magasin',
                'stock.context_processors.notifications_erp',
                'stock.context_processors.validation_menu_context',
                'stock.context_processors.validation_demandes_menu',
                'stock.context_processors.menu_validation_context',
                # ✅ CORRECTION : sélecteur d'établissement supprimé (mono-tenant)
                'accounts.context_processors.theme_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# ✅ CORRECTION : mot de passe lu depuis variable d'environnement
# Utilisation de SQLite pour les tests si DATABASE_URL non défini
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
    }
elif os.environ.get('TEST_MODE', 'False').lower() in ('true', '1', 'yes'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    if not os.environ.get('DB_PASSWORD') and not DEBUG:
        raise ImproperlyConfigured(
            "La variable d'environnement DB_PASSWORD doit être définie en production."
        )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'chu_angre_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'admin'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'fr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
# Securite renforcee (ERP sante)
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS : 'SAMEORIGIN' (défini plus bas) est volontaire :
# nécessaire pour les aperçus PDF affichés en iframe sur le même site.
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

# --- CONFIGURATION DE LA CONNEXION (Module accounts) ---
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# --- SÉCURITÉ DES SESSIONS ---
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 1200               # 20 minutes = 1200 secondes
SESSION_SAVE_EVERY_REQUEST = True       # Rafraîchit le timer à chaque clic


# Autoriser l'affichage des fenêtres pop-up (iframes) sur le même site
X_FRAME_OPTIONS = 'SAMEORIGIN'

# URL publique pour accéder aux fichiers
MEDIA_URL = '/media/'

# Dossier physique où les fichiers sont stockés
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# ✅ CORRECTION : Backend standard Django (plus de TenantAwareBackend)
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# ── Sécurité ─────────────────────────────────────────────────────────
# Activer UNIQUEMENT si l'application est derrière un reverse proxy qui
# écrase X-Forwarded-For (nginx, traefik…). Sinon, rester False : un
# client peut spoof cet en-tête pour contourner l'anti brute-force IP.
USE_X_FORWARDED_FOR = False
