# Generated by Django 6.1 on 2026-09-11 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
        ('stock', '0036_alter_historicalmouvement_type_mouvement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prevue', models.PositiveIntegerField(default=1)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stock.article')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Besoin de Projet',
                'verbose_name_plural': 'Besoins de Projets',
                'unique_together': {('projet', 'article')},
            },
        ),
    ]
