# Generated by Django 6.1 on 2026-09-11 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_projetbesoin'),
        ('stock', '0037_historicalmagasin_gere_projets_magasin_gere_projets'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojet',
            name='fournisseur',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.fournisseur', verbose_name='Fournisseur / Entreprise en charge'),
        ),
        migrations.AddField(
            model_name='projet',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='stock.fournisseur', verbose_name='Fournisseur / Entreprise en charge'),
        ),
    ]
