# Generated by Django 6.1 on 2026-09-11 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_historicalprojet_fournisseur_projet_fournisseur'),
        ('stock', '0037_historicalmagasin_gere_projets_magasin_gere_projets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proforma', models.CharField(db_index=True, max_length=100, verbose_name='Numéro / Réf Proforma')),
                ('date_proforma', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
                ('objet', models.CharField(blank=True, default='', max_length=255, verbose_name='Objet / Remarque')),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='projets/proformas/', verbose_name='Fichier scan / Devis')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ANNULE', 'Annulé')], db_index=True, default='ACTIF', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas_projet', to='stock.fournisseur', verbose_name='Fournisseur / Prestataire')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Proforma Projet',
                'verbose_name_plural': 'Proformas Projets',
                'ordering': ['-date_proforma', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProjetProformaLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prevue', models.PositiveIntegerField(default=1)),
                ('prix_unitaire_estime', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stock.article')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='projets.projetproforma')),
            ],
            options={
                'verbose_name': 'Ligne de Proforma',
                'verbose_name_plural': 'Lignes de Proforma',
            },
        ),
    ]
