# Generated by Django 6.1 on 2026-09-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_projetproforma_projetproformaligne'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojet',
            name='meme_fournisseur_livreur',
            field=models.BooleanField(default=True, help_text="Si activé, ce fournisseur sera automatiquement sélectionné lors des mouvements d'entrée de stock liés à ce projet.", verbose_name='Même fournisseur pour la livraison du matériel'),
        ),
        migrations.AddField(
            model_name='projet',
            name='meme_fournisseur_livreur',
            field=models.BooleanField(default=True, help_text="Si activé, ce fournisseur sera automatiquement sélectionné lors des mouvements d'entrée de stock liés à ce projet.", verbose_name='Même fournisseur pour la livraison du matériel'),
        ),
    ]
