# Generated by Django 6.1 on 2026-09-14 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_configurationhopital_pied_page_pdf_and_more'),
        ('projets', '0005_historicalprojet_meme_fournisseur_livreur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojet',
            name='direction_responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.service', verbose_name='Direction / Service responsable'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='responsable_direction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable / Signataire de la Direction'),
        ),
        migrations.AddField(
            model_name='projet',
            name='direction_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_direction', to='core.service', verbose_name='Direction / Service responsable'),
        ),
        migrations.AddField(
            model_name='projet',
            name='responsable_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_direction_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable / Signataire de la Direction'),
        ),
    ]
